### ISSUE TITLE
The custom token format is incorrect

### ISSUE THREAD

**Issue by ronlinet** [kreait/firebase-tokens-php#24]
I am using the bellow snippet to generate custom tokens for clients who are using my Flutter mobile app. 
 
```
$privateKey 	= json_decode(file_get_contents( storage_path()  . '/app/google-services.json'), true)['private_key'];
$generator 	    = CustomTokenGenerator::withClientEmailAndPrivateKey($clientEmail, $privateKey);
$token 		    = $generator->createCustomToken('uid', ['first_claim' => 'first_value' /* ... */]);
return json_encode(["status_code" => "200", "token" => $token->toString() ]);
 
```
When I am reusing the `$token->toString()` in my   `FirebaseAuth.instance.signInWithCustomToken ( token: '${httpResponse['token']}')` I get firebase error  “FirebaseAuthInvalidCredentialsException: The custom token format is incorrect.” .  

According to firebase group it is a generic error message for if the maximum expiration time is more than one hour 
https://groups.google.com/forum/#!msg/firebase-talk/tYRfde4nwBY/yAn5I_spBQAJ . Does the CustomTokenGenerator::withClientEmailAndPrivateKey take any maximum expiration time parameter? 

Also I wonder if the $token->toString() is the correct value which I should return from my server to my mobile app ?  

Thank you for you troubles.

**Comment by jeromegamez** [comment]
Hi @ronlinet and thanks for reaching out!

Custom tokens have [a TTL of one hour (3600 seconds) by default](https://github.com/kreait/firebase-tokens-php/blob/master/src/JWT/Action/CreateCustomToken.php#L13-L15) and the duration is [added to the current time](https://github.com/kreait/firebase-tokens-php/blob/master/src/JWT/Action/CreateCustomToken/WithLcobucciV3JWT.php#L47), so my assumption is that the time in your environment is ever so slightly ahead of the time on Google's servers.

As an example: if it's 12:00 on Google's Servers, but 12:01 in your environment, the token will be set to expire at 13:01. Since it's one minute earlier for Google, they say "wait, that's 61 minutes, but we only allow a maximum TTL of 60 minutes, so... no!"

I probably didn't need to explain this to you, I just added the explanation for others that might stumble upon this issue as well.

If you want to try out using a shorter TTL to see if this helps, you can use a third parameter on the `createCustomToken()` method with a custom TTL:

```php
$uid = 'uid';
$claims = [/* ... */];
$ttl = 1800; // or 'PT30M'

$token = $generator->createCustomToken($uid, $claims, $ttl);
```

But I would still recommend to check if the time in your environment is in sync with the world 🙈

---

The token string is the correct value, if you use it to sign-in with on the client-side, for example in the Web Client SDK as described here: https://firebase.google.com/docs/auth/web/custom-auth#authenticate-with-firebase

**Comment by ronlinet** [comment]
Hi @jeromegamez thank your for you qick feedback. 
To put you more in context... 

My firestore database rule is set as following 
`allow read : if request.auth != null;`



My web server server is acting as an authorization portal.
The clients are already authenticated with authorisation headers in my website.  
All I need is to blindely delivering the tokens to any http query that reaches the bellow php code.


```
$privateKey     = json_decode(file_get_contents( storage_path()  . '/app/google-services.json'), true)['private_key'];    
$generator      = CustomTokenGenerator::withClientEmailAndPrivateKey($clientEmail, $privateKey);                                                                                                               
token           = $generator->createCustomToken('uid', ['first_claim' => 'first_value' /* ... */], 'PT30M');    

return json_encode(["status_code" => "200", "token" => $token->toString() ]); 
```

As you see I have tried to set time for less then one minute but no chance the mobile app is throwing an invalid format execption. 
`Unhandled Exception: PlatformException(ERROR_INVALID_CUSTOM_TOKEN, The custom token format is incorrect. Please check the documentation., null)`

I have dumped the $token->toString()  what may be wrong tiwh format here ?     

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzdHVkZW50QHByb2QuY29tIiwic3ViIjoic3R1ZGVudEBwcm9kLmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9pZGVudGl0eXRvb2xraXQuZ29vZ2xlYXBpcy5jb21cL2dvb2dsZS5pZGVudGl0eS5pZGVudGl0eXRvb2xraXQudjEuSWRlbnRpdHlUb29sa2l0IiwiaWF0IjoxNTg2MjE1NzU1LCJleHAiOjE1ODYyMTc1NTUsInVpZCI6InVpZCIsImNsYWltcyI6eyJmaXJzdF9jbGFpbSI6ImZpcnN0X3ZhbHVlIn19.J8uN3ybYYqvRkMFVE3dCSmFVnibJ7ZLCA_noFhZaGGBX_DBB9RFXjMOyVaSOEUxy_fYQB8sgf6LMNNKxyJlCcUS9AiQ2mILuFsuyL5TLhCHgn6AG3vJn_w4dZM8xH_l-iyskfVMA0fTWTisTgLoLMDzqZsE8e4tXdpYjZGFnLBn7IvY1KFJVWTOlkHlzh63r5gfh08VFFMuMHvIBxWs7ijVOFgEnRY5G54OgnXIEMl1D_CgaGW_lV88Z3k9mJwh9Por5S3FLQwE9X7ZzjLDz9QIk3QKnSdN0OioxMkH56i9f77Rjw5v3Dg1LUOV3Vepr2BHhuBU05BDpwi_dopvIdw
```

PS: I will see about the time server and google API time.

**Comment by jeromegamez** [comment]
I noticed that you don‘t seem retrieve the client email from the JSON file as you do with the private key - is this really the case? If so, could you make sure that the client email you‘re using matches the value in the JSON file?

Beside that I currently have no idea what might be the issue, but I‘ll make sure to try it myself as well as soon as I‘m back at my computer. 🤞

**Comment by jeromegamez** [comment]
I just tested this with my project with the help of [`kreait/firebase-php`](https://github.com/kreait/firebase-php) and it works for me™. So a possibly mismatching client email is the only possible issue left that I could think of.

I just also noticed that you seem to be using Laravel/Lumen - have you considered using https://github.com/kreait/laravel-firebase or is it too heavy for your use case?

**Comment by ronlinet** [comment]
Casting the token object to string is the solution in my case. 
@jeromegamez thank you for your time, much appreciated. 
Working snippet : 
```
use Kreait\Firebase\ServiceAccount;
use Kreait\Firebase\Factory; 
$serviceAccount = ServiceAccount::fromJsonFile( storage_path()  . '/app/google-services.json');
$firebase = (new Factory)
                        ->withServiceAccount($serviceAccount)
                        ->create();
$token = $firebase->getAuth()->createCustomToken($request->header('PHP_AUTH_USER'));
return json_encode(["status_code" => "200", "token" => (string) $token ]);
```

**Comment by jeromegamez** [comment]
Aaaah! My mistake, you‘re right! I forgot that lcobucci/jwt has different outputs of `toString()` vs casting the object 🙈, and I apparently didn‘t fully test the same procedure that you used 😅. Kudos for getting to a solution, and thanks for sharing! 🌺
