### ISSUE TITLE
Maxium Expiration Time duration flexiblity

### ISSUE THREAD

**Issue by lyntonds** [kreait/firebase-tokens-php#27]
In src/JWT/action/CreateCustomToken.php

MAXIMUM_TTL is set to PHT1H  which expires in an hour i want it P1D

Even your function createCustomToken doens't let me go beyond 1 Hour can you remove the validation or provide a solution.

Thanks

**Comment by jeromegamez** [comment]
The Maximum TTL is set to 1 hour, because that's the maximum firebase allows: https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library

![image](https://user-images.githubusercontent.com/67554/87043910-17955680-c1f6-11ea-97fa-fa2780b4eb42.png)

**Comment by lyntonds** [comment]
That's the maximum Firebase allows, cool. Thanks for your feedback.
